version: '3'
services:
  photoapp:
    build:
      context: ./docker/photoapp
    ports:
      - '9000:80'
    volumes:
      - ./photoapp:/var/www/photoapp/
    working_dir: /var/www/photoapp
    depends_on:
      - mysql
    environment:
      TZ: Asia/Tokyo

  mysql:
    build:
      context: ./docker/mysql
    ports:
      - "32800:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: Asia/Tokyo
